tugas/sim/mahasiswa/routes.py
from flask import Flask, render_template, url_for, redirect, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F,editpengaduan_F
from sim.models import Tmahasiswa, Tpengaduan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image


rmahasiswa= Blueprint('rmahasiswa',__name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html")

@rmahasiswa.route("/data-mahasiswa", methods=['GET','POST'])
def data_mahasiswa():
    form=mahasiswa_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data, password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun -{form.npm.data} berhasil Terdaftar','info')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data_mahasiswa.html", form=form)

@rmahasiswa.route("/login_mahasiswa", methods=['GET','POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form=loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm=Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('selamat Datang Kembali !!')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('login gagal')
    return render_template("login_mahasiswa.html",form=form)

@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template("akunmahasiswa.html ")


@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))
# simpaan foto

def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn= random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    # form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/edit_mahasiswa", methods=['GET','POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto= file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.password=pass_hash
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        db.session.commit()
        flash('Data Barhasil Diubah!','warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
       form.npm.data= current_user.npm
       form.nama.data=current_user.nama
       form.email.data= current_user.email
       form.password.data= current_user.password
       form.kelas.data=current_user.kelas
       form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form)

@rmahasiswa.route("/pengaduan/", methods=['GET','POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        add_pengaduan= Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data Barhasil Ditambahkan','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)


@rmahasiswa.route("/updatepengaduan/<int:ed_id>/update", methods=['GET','POST'])
@login_required
def edt_pengaduan(ed_id): 
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    elif form.validate_on_submit():
        dt_pengaduan.subjek= form.subjek.data
        dt_pengaduan.kategori= form.kategori.data
        dt_pengaduan.detail_pengaduan= form.detail_pengaduan.data
        db.session.commit()
        flash("data berhasil diubah!")
    return render_template('edit_pengaduan.html', form=form)


@rmahasiswa.route("/hapuspengaduan/<id>", methods=['GET','POST'])
@login_required
def hps_pengaduan(id):
        h_pengaduan=Tpengaduan.query.get(id)
        db.session.delete(h_pengaduan)
        db.session.commit()
        flash('Data Berhasil Dihapus')
        return redirect(url_for('rmahasiswa.pengaduan'))


@rmahasiswa.route("/pengaduan/<int:ed_id>/Detail", methods=['GET','POST'])
@login_required
def ket_pengaduan(ed_id): 
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('ket_pengaduan.html', dt_pengaduan=dt_pengaduan)


@rmahasiswa.route("/tentang")
def tentang():
    return render_template("tentang.html ")

tugas/sim/templates/akunmahasiswa.html
{% extends "base.html" %}

{% block konten %}

<div class="jumbotron">
    <h1 class="display-4">Hallo,{{current_user.nama}} !</h1>
    <p class="lead">Selamat Datang Di Sistem Pengaduan</p>
    <hr class="my-4">
    <p>Masuk Disini Untuk Membuat Pengaduan </p>
    <a class="btn btn-primary btn-lg" href="{{url_for('rmahasiswa.pengaduan')}}" role="button">Pengaduan</a>
  </div>
{% endblock %}

tugas/sim/templates/base.html
<html>
    <head>
        <title>Website</title>
        <link rel="stylesheet" href="{{url_for ('static', filename="css/bootstrap.min.css")}}" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{url_for ('static', filename="css/style.css")}}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container">
            <a class="navbar-brand" href="#">Menu</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{url_for('rmahasiswa.home')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('rmahasiswa.tentang')}}">Tentang</a>
                </li>
                {% if current_user.is_authenticated %}
                {% else%}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
                </li>
                {% endif%}
                
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-secondary my-0 my-sm-3" type="submit">Search</button>
              </form>
            </div>
        </div>
          </nav>

        <div class="konten">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-md-8">
                        <div class="shadow p-3 mb-5 bg-white rounded">
                          
                            {% with messages = get_flashed_messages(with_categories=true)%}
                              {% if massages %}
                                {% for category, massage in massages %}
                                  <div class="alert alert-{{category}}">
                                       {{massage}} 
                                  </div>
                                {% endfor %}
                              {% endif %}
                            {% endwith %}

                          {% block konten %}

                          {% endblock %}

                        </div>
                    </div>

                    <div class="col-md-4">
                      <div class="shadow p-3 mb-5 bg-white rounded">

                        <h4>Menu Pilihan</h4>
                        {% if current_user.is_authenticated %}
                        <div class="card" style="width: 15rem;">
                          <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top" alt="...">
                          <div class="card-body">
                            <h5 class="card-title">{{current_user.nama}}</h5>
                            <p class="card-text">{{current_user.email}} </p>
                          </div>
                          <ul class="list-group list-group-flush">
                            <li class="list-group-item"> <a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dasboard</a></li>
                            <li class="list-group-item"> <a href="{{url_for('rmahasiswa.pengaduan')}}">Pengaduan</a></li>
                      
                          </ul>
                          <div class="card-body">
                            <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                            <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Keluar</a>
                          </div>
                        </div>
                        
                        {% else %}
                        <li>Data Kampus</li>
                        <li>Data Dosen</li>
                        {% endif%}
                         
                      </div>
                  
                    </div>
                </div>  
            </div>
        </div>

    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="{{url_for ('static', filename="js/bootstrap.min.js")}}" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


</html>

tugas/sim/templates/data_mahasiswa.html
{% extends "base.html" %}

{% block konten %}
<h2>Daftar  Akun </h2>
<form method="POST">
      {{form.hidden_tag()}}
    <div class="form-group">
      {{form.npm.label(class="form-control-label")}}
      {% if form.npm.errors %}
        {{form.npm(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.npm.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.npm(class="form-control")}} 
      {% endif%}
    </div>


    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>

    <div class="form-group">

        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
        {{form.email(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
      {{form.email(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.password(class="form-control")}} 
      {% endif%}
    </div>
    <div class="form-group">
      {{form.konf_pass.label(class="form-control-label")}}
      {% if form.konf_pass.errors %}
        {{form.konf_pass(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.konf_pass.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.konf_pass(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
        {{form.kelas.label(class="form-control-label")}}
        {{form.kelas(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
    
    
  </form>


<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint consequatur corporis, voluptas voluptatum, repellendus totam perspiciatis esse quidem quia ratione eveniet. Nam provident sit rerum ducimus aut in! Molestiae, nisi.</p>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
    Ducimus quas eos, ea repellat qui tenetur fuga commodi et aliquid nulla 
    reiciendis animi ipsa reprehenderit nesciunt vel fugit ad! Deleniti, natus.</p> 
 



{% endblock %}

tugas/sim/templates/edit_mahasiswa.html
{% extends "base.html" %}

{% block konten %}
<h2>Update Data Akun </h2>
<form method="POST" enctype="multipart/form-data">
      {{form.hidden_tag()}}
    <div class="form-group">
      {{form.npm.label(class="form-control-label")}}
      {% if form.npm.errors %}
        {{form.npm(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.npm.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.npm(class="form-control")}} 
      {% endif%}
    </div>


    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>

    <div class="form-group">

        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
        {{form.email(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
      {{form.email(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.password(class="form-control")}} 
      {% endif%}
    </div>
    <div class="form-group">
      {{form.konf_pass.label(class="form-control-label")}}
      {% if form.konf_pass.errors %}
        {{form.konf_pass(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.konf_pass.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.konf_pass(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
        {{form.kelas.label(class="form-control-label")}}
        {{form.kelas(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group">
      {{form.foto.label(class="form-control-label")}}
      {% if form.foto.errors %}
        {{form.foto(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.foto.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.foto(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
    
    
  </form>


<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint consequatur corporis, voluptas voluptatum, repellendus totam perspiciatis esse quidem quia ratione eveniet. Nam provident sit rerum ducimus aut in! Molestiae, nisi.</p>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
    Ducimus quas eos, ea repellat qui tenetur fuga commodi et aliquid nulla 
    reiciendis animi ipsa reprehenderit nesciunt vel fugit ad! Deleniti, natus.</p> 
 



{% endblock %}

tugas/sim/templates/edit_pengaduan.html
{% extends "base.html" %}

{% block konten %}

<div class="jumbotron">
   
    <p class="lead"> Update Pengaduan</p>
    <hr class="my-4">
    <!--pegaduan-->
    <form method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.subjek.label(class="form-control-label")}}
        {% if form.subjek.errors %}
          {{form.subjek(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.subjek.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.subjek(class="form-control")}} 
        {% endif%}
      </div>
      
      <div class="form-group">
        {{form.kategori.label(class="form-control-label")}}
        {% if form.kategori.errors %}
          {{form.kategori(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.kategori.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.kategori(class="form-control")}} 
        {% endif%}
      </div>
      <div class="form-group">
        {{form.detail_pengaduan.label(class="form-control-label")}}
        {% if form.detail_pengaduan.errors %}
          {{form.detail_pengaduan(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.detail_pengaduan.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.detail_pengaduan(class="form-control")}} 
        {% endif%}
      </div>
  
      <div class="form-group" onclick="return alert('Data Telah Berhasil Disimpan, klik kembali untuk memulai pengaduan')">
          {{form.submit(class="btn btn-danger btn-sm")}}
          
      </div>
      <a href="{{url_for('rmahasiswa.pengaduan')}}" class=" btn btn-primary btn-sm">Kembali</a>
      
    </form>
        


  
  </div>

{% endblock %}

tugas/sim/templates/home.html
{% extends "base.html" %}

{% block konten %}

<div class="jumbotron">
    <h1 class="display-4">Hallo, Selamat Datang!</h1>
    <p class="lead">Sistem Pengaduan Mahasiswa.</p>
    <hr class="my-4">
    <p><i>Apapun yang dilakukan oleh seseorang itu, hendaknya dapat bermanfaat bagi dirinya sendiri, bermanfaat bagi bangsanya, dan bermanfaat bagi manusia di dunia pada umumnya". - Ki Hadjar Dewantara</i> </p>
    <a class="btn btn-primary btn-lg" href="{{url_for('rmahasiswa.login_mahasiswa')}}" role="button">Masuk </a>
  </div>
{% endblock %}

tugas/sim/templates/kelas.html
<html>
    <head>
        <title> Website </title>
    </head> 

    <body>
        <h4>Kelas Yang Tersedia</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Dicta veniam amet esse, nulla eaque laborum atque facere
        pariatur maxime praesentium laboriosam aspernatur debitis 
        quibusdam eos ab culpa quia impedit commodi?</p>
    </body>     
    
</html>

tugas/sim/templates/ket_pengaduan.html
{% extends "base.html" %}

{% block konten %}
<h3>Detail Akun</h3>
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Selamat Datang!</h4>
  <p>Informasi data akun yang telah terdaftar</p>
  <hr>
  <p class="mb-10 "></p>
  
  <table class="table table-hover">
      <tr class="">
          <td>NPM</td>
          <td>{{dt_pengaduan.mahasiswa.npm}}</td>
      </tr>

      <tr  >
          <td>Nama</td>
          <td>{{dt_pengaduan.mahasiswa.nama}}</td>
      </tr>

      <tr>
          <td>Email</td>
          <td>{{dt_pengaduan.mahasiswa.email}}</td>
      </tr>

      <tr >
          <td>Alamat</td>
          <td>{{dt_pengaduan.mahasiswa.alamat}}</td>
      </tr>

      <tr >
          <td>Kelas</td>
          <td>{{dt_pengaduan.mahasiswa.kelas}}</td>
      </tr>


  </table>


</div>
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Detail Pengaduan</h4>
      <p>Informasi data pengaduan yang telah terdaftar</p>
      <hr>
      <p class="mb-10 "></p>
      
      <table class="table table-hover">
          <tr class="">
              <td>Tanggal Post</td>
              <td>{{dt_pengaduan.tgl_post}}</td>
          </tr>

          <tr  >
              <td>Subjek</td>
              <td>{{dt_pengaduan.subjek}}</td>
          </tr>

          <tr>
              <td>Kategori Pengaduan</td>
              <td>{{dt_pengaduan.kategori}}</td>
          </tr>

          <tr >
              <td>Detail Pengaduan</td>
              <td>{{dt_pengaduan.detail_pengaduan}}</td>
          </tr>
      </table>
    </div>

{% endblock %}

tugas/sim/templates/kontak.html
{% extends "base.html" %}

{% block konten %}
<h3>Kontak yang bisa dihubungi :</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Ipsum eum totam repellendus ea quaerat. 
            Quaerat quis quae voluptatibus repellat aperiam! Doloremque, 
            tenetur esse. Quas, eos sit blanditiis placeat necessitatibus minima.</p>
            <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae, 
            distinctio repudiandae vel placeat soluta quidem voluptas assumenda 
            enim velit veritatis amet culpa ea reprehenderit repellat consequatur 
            provident dolorem error aliquid!
            </p>  
{% endblock %}

tugas/sim/templates/login_mahasiswa.html
{% extends "base.html" %}

{% block konten %}
<h2>Login Mahasiswa </h2>
<form method="POST">
      {{form.hidden_tag()}}
    <div class="form-group">
      {{form.npm.label(class="form-control-label")}}
      {% if form.npm.errors %}
        {{form.npm(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.npm.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.npm(class="form-control")}} 
      {% endif%}
    </div>

    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}} 
        
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
      {% else%}
        {{form.password(class="form-control")}} 
      {% endif%}
    </div>


    <div class="Login">
        {{form.submit(class="btn btn-primary")}}
    </div>

    <span> <a href="{{url_for('rmahasiswa.data_mahasiswa')}}">Daftar Akun</a></span>
    
  </form>


<p>Login untuk membuat pengaduan</p>

 



{% endblock %}

tugas/sim/templates/pengaduan.html
{% extends "base.html" %}

{% block konten %}

<div class="jumbotron">
   
    <p class="lead"> <b> <h4>Pengaduan</h4> </b> </p>
    <hr class="my-4">
    <!--pegaduan-->
    <form method="POST">
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.subjek.label(class="form-control-label")}}
        {% if form.subjek.errors %}
          {{form.subjek(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.subjek.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.subjek(class="form-control")}} 
        {% endif%}
      </div>
      
      <div class="form-group">
        {{form.kategori.label(class="form-control-label")}}
        {% if form.kategori.errors %}
          {{form.kategori(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.kategori.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.kategori(class="form-control")}} 
        {% endif%}
      </div>
      <div class="form-group">
        {{form.detail_pengaduan.label(class="form-control-label")}}
        {% if form.detail_pengaduan.errors %}
          {{form.detail_pengaduan(class="form-control is-invalid")}} 
          
          <div class="invalid-feedback">
            {% for error in form.detail_pengaduan.errors %}
            <span>{{error}}</span>
            {% endfor %}
          </div>
        {% else%}
          {{form.detail_pengaduan(class="form-control")}} 
        {% endif%}
      </div>
  
      <div class="form-group">
          {{form.submit(class="btn btn-primary")}}
      </div>
      
    </form>
        <hr class="my-4">
        <h4>Data Pengaduan</h4>
        <table class="table table-responsive table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID Mahasiswa</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Subjek</th>
                <th scope="col">Edit</th>
                <th scope="col">Hapus</th>
            </tr>
            </thead>
            <tbody>
            {%for data in dt_pengaduan%}  
            <tr>
                
                <th > <a href="{{url_for('rmahasiswa.ket_pengaduan',ed_id=data.id)}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-person" viewBox="0 0 16 16">
                  <path d="M11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                  <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2v9.255S12 12 8 12s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h5.5v2z"/>
                </svg></a></th>
                 <td>{{data.mahasiswa_id}}</td>
                 <td>{{data.tgl_post}}</td>
                <td>{{data.subjek}}</td>
                <td> <a href="{{url_for('rmahasiswa.edt_pengaduan', ed_id=data.id)}}" class="btn btn-primary btn-sm">Edit</a> </td>
                <td> <a href="/hapuspengaduan/{{data.id}}" class="btn btn-danger btn-sm" onclick="return confirm('anda yakin untuk menghapus data')"> Hapus</a></td>
            </tr>


            {% endfor %}

            <!-- Small modal -->
            

            </tbody>
        </table>

  </div>

{% endblock %}

tugas/sim/templates/tentang.html
{% extends "base.html" %}

{% block konten %}
<h2>Tentang Website Kami</h2>

    <p>Website ini dibangun sebagai fasilitas pengaduan mahasiswa kampus yang telah terdaftar</p>
    <p>Hub : Ummi Kalsum Dari info1</p>

{% endblock %}